spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order
        - id: eureka-server
          uri: lb://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: lb://localhost:8761
          predicates:
            - Path=/eureka/**
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/chiba-store


eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
logging:
  level:
    root: info

server:
  port: 3000
management:
  endpoints:
    web:
      exposure:
        include: prometheus
